package com.jacrispys.JavaBot.Utils;


import com.jacrispys.JavaBot.Utils.ExperimentalUtils.Experimental;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Member;
import net.dv8tion.jda.api.entities.TextChannel;

import java.awt.*;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeUnit;

public class GameSpyThread extends Thread {

    private final JDA jda;
    public List<Guild> runningSpies = new ArrayList<>();

    public GameSpyThread(JDA jda) {
        this.jda = jda;
    }

    @Override
    public void run() {
        System.out.println("Thread running!");

    }

    public void addNewSpy(Guild guild) {
        runningSpies.add(guild);
    }

    @Experimental("Can override existing data! Only use if you must!")
    public void setSpyList(List<Guild> guildList) {
        runningSpies = guildList;
    }

    public List<Guild> getRunningSpies() {
        return runningSpies;
    }


    public void runSpy(Guild guild) {
        TextChannel gameSpyChannel = guild.getTextChannelById(Long.parseLong((String) ChannelStorageManager.getInstance().getGuildData(guild, "gameSpyChannel")));

        gameSpyChannel.sendMessage("Currently Crunching numbers from: " + guild.getName()).queue();

        EmbedBuilder embedBuilder = new EmbedBuilder();
        embedBuilder.setTitle("GameSpy™ Report");
        embedBuilder.setColor(new Color(0x530C84));
        embedBuilder.setDescription("Generated by SSB on: " + LocalDate.now() + "\n");
        embedBuilder.setAuthor("Made & Maintained by: Jacrispys");
        embedBuilder.setImage("https://i.imgur.com/MD8RHHL.png");

        StringBuilder richValue = new StringBuilder();
        for (Member member : guild.getMembers()) {
            for (Activity activity : member.getActivities()) {
                String time;
                if (activity.getTimestamps() != null) {
                    long secs = activity.getTimestamps().getElapsedTime(ChronoUnit.SECONDS);
                    time = String.format("%02d:%02d:%02d", secs / 3600, (secs % 3600) / 60, secs % 60);
                    richValue.append("\n" + member.getAsMention() + " - " + activity.getName() + " for " + time);
                }
            }
        }

        if(richValue.toString().length() >= 1024 && richValue.toString().length() <= 2048) {
            embedBuilder.addField("*Games*", richValue.substring(0,1024), false);
            embedBuilder.addField("*Games (Cont)*", richValue.substring(1024,richValue.toString().length()), false);
        } else {
            embedBuilder.addField("*Games*", richValue.toString(), false);
        }

        gameSpyChannel.sendMessageEmbeds(embedBuilder.build()).queue();
    }
}
